name: 'Release v$NEXT_RELEASE'
tag: 'v$NEXT_RELEASE'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: 'Features'
    label: 'feat'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Refactors'
    label: 'refactor'
  - title: 'Maintenance'
    label: 'chore'
changelog-path: CHANGELOG.md
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'minor'
  default: patch
template: |
  ## What's changed

  $CHANGES