name: Release

on:
  release:
    types: [published]

jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y gettext
      - uses: actions/setup-python@v4.2.0
      - uses: actions/setup-node@v3.4.1
      - uses: actions/checkout@v3
      - name: Install Javascript dependencies
        working-directory: ./django_ckeditor_5
        run: npm install
      - name: Build ck-editor
        working-directory: ./django_ckeditor_5
        run: npm run prod
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip build wheel twine
      - name: Build dist packages
        run: python -m build --sdist --wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  update-changelog:
    runs-on: ubuntu-latest
    needs: PyPI
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install release-drafter
        run: |
          python -m pip install release-drafter
      - name: Update changelog
        run: release-drafter --token ${{ secrets.GITHUB_TOKEN }}